### ISSUE TITLE
New feacture: print partner vat

### ISSUE THREAD

**Issue by cholitoecuatoriano** [Vauxoo/addons-clearcorp#499]
Please add feacture, print partner vat in receipt.

**Comment by ghost** [comment]
Hi cholitoecuatoriano,
Thanks for writing. 
We can help you to integrate souce code to improve our modules. Do you have the changes to improve that?

**Comment by cholitoecuatoriano** [comment]
In /pos_receipt/static/src/xmlmain.xml After line Client
`Client VAT: <t t-esc="receipt.client.vat ? order.attributes.client.vat : ''"/><br />`

**Comment by ghost** [comment]
Thank you, we will review this code

**Comment by ghost** [comment]
Add the changes to the source code on pull request 509

Regards,
