### ISSUE TITLE
I found An error occurred while parsing the view into file.

### ISSUE THREAD

**Issue by afrijaldz** [Vauxoo/addons-clearcorp#731]
I'm sorry for the bad question, I try to install this module in odoo 9 without any script edited. And when I print using report xls i found that error. Would you explain to me how it can happen?

Thanks a lot for answer.

**Comment by carlosrve** [comment]
Hi @afrijaldz,

Which module are you refering to? This repository has many modules. Also, what commit are you using to test.

And most important, what error did you encounter?

Thank you,

**Comment by afrijaldz** [comment]
Thanks for answer

Here I'm using report_xls_template with branch 9.0 and I install it in my odoo 9..
i found error, when I try to print report in xls and it shows dialog An error occurred while parsing the view into file.

**Comment by carlosrve** [comment]
And what is the error?

**Comment by afrijaldz** [comment]
hehehe sorry, the error is put qweb in the xml in view/account_invoice_report.xml. could you give me information about it?

**Comment by carlosrve** [comment]
Hi,

I will need the full error traceback log, and a link to you code in github
so I can understand what you are doing.

Regards,
